/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lasersnake;

import static lasersnake.LaserSnake.ResourceLoader;
import static lasersnake.LaserSnake.cardLayout;
import static lasersnake.LaserSnake.currentMusic;
import static lasersnake.LaserSnake.currentState;
import static lasersnake.LaserSnake.playMusic;
import static lasersnake.LaserSnake.rewindMusic;
import static lasersnake.LaserSnake.rootPanel;
import static lasersnake.LaserSnake.stopMusic;

/**
 *
 * @author Nicholas
 */
public class AboutPanel extends javax.swing.JPanel {

    /**
     * Creates new form AboutPanel
     */
    public AboutPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainmenu = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainmenu.setBackground(new java.awt.Color(0, 250, 135));
        mainmenu.setText("Main Menu");
        mainmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainmenuActionPerformed(evt);
            }
        });
        add(mainmenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 480, 160, 80));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/about.jpg"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void mainmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainmenuActionPerformed
        DrawSnake.resetBoard();
        cardLayout.show(rootPanel, "main");
        currentState = LaserSnake.gameState.mainMenu;
        stopMusic();
        rewindMusic(currentMusic);
        playMusic(ResourceLoader.menuMusic);
    }//GEN-LAST:event_mainmenuActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton mainmenu;
    // End of variables declaration//GEN-END:variables
}
