/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lasersnake;

import static lasersnake.LaserSnake.ResourceLoader;
import static lasersnake.LaserSnake.cardLayout;
import static lasersnake.LaserSnake.currentMusic;
import static lasersnake.LaserSnake.currentState;
import static lasersnake.LaserSnake.gameDifficulty;
import static lasersnake.LaserSnake.playMusic;
import static lasersnake.LaserSnake.rewindMusic;
import static lasersnake.LaserSnake.runGame;
import static lasersnake.LaserSnake.stopMusic;
import static lasersnake.LaserSnake.twoPlayer;

/**
 *
 * @author Nicholas
 */
public class MainMenu extends javax.swing.JPanel {

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DifficultyButton = new javax.swing.JButton();
        PlayersButton = new javax.swing.JButton();
        StartButton = new javax.swing.JButton();
        AboutAndCredits = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        DifficultyButton.setText("Normal");
        DifficultyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DifficultyButtonActionPerformed(evt);
            }
        });
        add(DifficultyButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 380, 100, -1));

        PlayersButton.setText("One Player");
        PlayersButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlayersButtonActionPerformed(evt);
            }
        });
        add(PlayersButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 340, 100, -1));

        StartButton.setText("Start");
        StartButton.setMaximumSize(new java.awt.Dimension(85, 23));
        StartButton.setMinimumSize(new java.awt.Dimension(85, 23));
        StartButton.setPreferredSize(new java.awt.Dimension(85, 23));
        StartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartButtonActionPerformed(evt);
            }
        });
        add(StartButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 300, 100, -1));

        AboutAndCredits.setText("About");
        AboutAndCredits.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AboutAndCreditsActionPerformed(evt);
            }
        });
        add(AboutAndCredits, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 420, 100, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/mainMenu_alt.jpg"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void StartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartButtonActionPerformed
        currentState = LaserSnake.gameState.play;
        LaserSnake.cardLayout.show(LaserSnake.rootPanel, "game");
        DrawSnake.resetBoard();
        LaserSnake.rewindMusic(LaserSnake.currentMusic);
        runGame(LaserSnake.rootPanel, LaserSnake.gamePanel);
    }//GEN-LAST:event_StartButtonActionPerformed

    private void DifficultyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DifficultyButtonActionPerformed
        if(gameDifficulty == LaserSnake.difficulty.normal){
            gameDifficulty = LaserSnake.difficulty.hard;
            LaserSnake.speed = LaserSnake.HARD;
            DifficultyButton.setText("Hard");
        }
        else if(gameDifficulty == LaserSnake.difficulty.hard){
            gameDifficulty = LaserSnake.difficulty.insane;
            LaserSnake.speed = LaserSnake.INSANE;
            DifficultyButton.setText("Insane!");
        }
        else if(gameDifficulty == LaserSnake.difficulty.insane){
            gameDifficulty = LaserSnake.difficulty.easy;
            LaserSnake.speed = LaserSnake.EASY;
            DifficultyButton.setText("Easy");
        }
        else if(gameDifficulty == LaserSnake.difficulty.easy){
            gameDifficulty = LaserSnake.difficulty.normal;
            LaserSnake.speed = LaserSnake.NORMAL;
            DifficultyButton.setText("Normal");
                }
    }//GEN-LAST:event_DifficultyButtonActionPerformed

    private void PlayersButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlayersButtonActionPerformed
        if(twoPlayer == false){
                    twoPlayer = true;
                    PlayersButton.setText("Two Player");
                }
                else if(twoPlayer == true){
                    twoPlayer = false;
                    PlayersButton.setText("One Player");
                } 
    }//GEN-LAST:event_PlayersButtonActionPerformed

    private void AboutAndCreditsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AboutAndCreditsActionPerformed
        cardLayout.show(LaserSnake.rootPanel, "about");
        stopMusic();
        rewindMusic(currentMusic);
        playMusic(ResourceLoader.aboutMusic);
    }//GEN-LAST:event_AboutAndCreditsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AboutAndCredits;
    private javax.swing.JButton DifficultyButton;
    private javax.swing.JButton PlayersButton;
    private javax.swing.JButton StartButton;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
